### ISSUE TITLE
Tooltip with code for effect.

### ISSUE THREAD

**Issue by TinyChief** [emilkowalski/css-effects-snippets#4]
What do you think about adding a tooltip with `CSS`, when hovering an effect?

**Comment by davidescarioni** [comment]
I try to realize what @TinyChief says, but the problem is that the _pseudo-elements_ _after_ and _before_ are render only inside the border of the element. So you can use the only-css solution in very restricted case. 

`.tooltip {
  display: inline-block;
  justify-content: center;
  align-items: center;
  padding: 20px 20px;
  text-align: center;
  overflow: hidden;
  color: #474E51;
  position: relative;
}

.tooltip::after {
  content: "tooltip";
  position: absolute;
  left: 20%;
  background-color: black;
  color: #fff;
  opacity: 0;
  border-radius: 5px;
  padding: 2px;
  transition: all .5s;
}

.tooltip:hover::after {
    opacity: 1;
    -webkit-transform: translateY(-90%);
    -moz-transform: translateY(-90%);
    -ms-transform: translateY(-90%);
    -o-transform: translateY(-90%);
    transform: translateY(-90%);
}`

**Comment by TinyChief** [comment]
I mean tooltips like [this](https://vuetifyjs.com/en/components/tooltips#tooltip). Or we can use any other CSS library that has tooltips.

**Comment by davidescarioni** [comment]
Like [this](https://jsfiddle.net/Davide_Scarioni/k8y6hgjf/)?

**Comment by TinyChief** [comment]
Yes. The native implementation also will be cool!
